### ISSUE TITLE
Problem with absolute_path. Format but not save the file.

### ISSUE THREAD

**Issue by Bernardoow** [evancz/elm-format-on-save#2]
I use linux and yarn to install my npm packages.

When I save following message is show up.
```bash
OTE: Your PATH variable led me to check in the following directories:

    /home/bernardo/.cargo/bin
    /home/bernardo/bin
    /home/bernardo/.local/bin
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /usr/games
    /usr/local/games
```

When I type the following command

```bash
which elm-format
/home/bernardo/.yarn/bin/elm-format
```

So I check the settings at sublime about elm-format-on-save and found the setting **absolute_path**. I put the path of elm-format :
```json
{
    "absolute_path": "/home/bernardo/.yarn/bin/elm-format"
}
```

In this moment the format is working but the file isn't saved.

Look the problem:
![gif_to_show_the_problem_elm_format](https://user-images.githubusercontent.com/4077212/66214381-fa948b80-e697-11e9-846f-31f51e00b39b.gif)

**Comment by evancz** [comment]
I was not able to reproduce this on my computer.

Can you share your OS, version of Sublime Text, and any other details of your computer that may be relevant?

I believe any errors in a plugin script will show in **Sublime Text -> View -> Show Console** so there may be useful information for me in there as well.

**Comment by Bernardoow** [comment]
@evancz 

Sorry about this. Today it's working normally. I don't know what happend. Sorry again.

**Comment by evancz** [comment]
No worries, glad it is working!
